# repos:
#   - repo: https://github.com/psf/black
#     rev: 24.4.2
#     hooks:
#       - id: black
#   - repo: https://github.com/pycqa/flake8
#     rev: 7.1.0
#     hooks:
#       - id: flake8
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0
#     hooks:
#       - id: check-toml
#       - id: check-yaml
#       - id: end-of-file-fixer
#       - id: trailing-whitespace

repos:
  # - repo: https://github.com/psf/black
  #   rev: 24.4.2
  #   hooks:
  #     - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/numpy/numpydoc
    rev: v1.6.0
    hooks:
      - id: numpydoc-validation
        exclude: (^tests/.*)|(^docs/.*)|(^.*__init__\.py$)
